services:
  auto-paint-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: officina_app
    ports:
       - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      # - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
      - /app/node_modules
    restart: unless-stopped
    networks:
      - officina_app-network
      
networks:
  officina_app-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local