version: '3.8'

services:
  auto-paint-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-paint-pro-app
    ports:
      - "3002:3002"
    volumes:
      # Volume persistente para o banco SQLite
      - auto_paint_data:/app/data
      # Para desenvolvimento - descomente para hot reload
      # - .:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3002
    restart: unless-stopped
    networks:
      - auto-paint-network

  # Serviço opcional para desenvolvimento com hot reload
  auto-paint-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auto-paint-pro-dev
    ports:
      - "3002:3002"
    volumes:
      # Volume persistente para o banco SQLite
      - auto_paint_data:/app/data
      # Para desenvolvimento - descomente para hot reload
      # - .:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
    command: npm run dev
    restart: unless-stopped
    networks:
      - auto-paint-network
    profiles:
      - dev

networks:
  auto-paint-network:
    driver: bridge

volumes:
  auto_paint_data:
    driver: local