services:
  auto-paint-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-paint-pro-app
    ports:
       - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      - ./data:/app/data
      - /app/node_modules
    restart: unless-stopped
    networks:
      - auto-paint-network
      
networks:
  auto-paint-network:
    driver: bridge