services:
  auto-paint-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-paint-pro-app
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - auto-paint-network

  # Serviço opcional para desenvolvimento com hot reload
  auto-paint-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-paint-pro-dev
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    restart: unless-stopped
    networks:
      - auto-paint-network
    profiles:
      - dev

networks:
  auto-paint-network:
    driver: bridge

volumes:
  auto_paint_data:
    driver: local